name: data_gov_ua_statistic
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  json_annotation: 4.9.0
  freezed_annotation: ^2.4.4
  fl_chart: ^0.69.2
  intl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  build_runner: ^2.4.13
  json_serializable: 6.8.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - data/144-zovnishnia-torgivlia-tovarami-u-dinamitsi.json
